name: nakama-node-jp1

database:
  address:
    - "root:sparkinfi123!@192.168.102.223:5432?dbname=test"
  max_open_conns: 30
  max_idle_conns: 10
logger:
  level: "debug"

session:
  encryption_key: "defaultencryptionkey"
  token_expiry_sec: 86400
  refresh_encryption_key: "defaultrefreshencryptionkey"
  refresh_token_expiry_sec: 186400
  single_socket: true
  single_session: true

cluster:
  enabled: true
  redis_address: "192.168.102.223:6379"
  redis_password: ""
  redis_db: 0

socket:
  server_key: "sparkgame"
  port: 7350

console:
  port: 7351
  username: "admin"
  password: "password"

social:
  alipay:
    app_id: "2060170000379801"
    private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDeimJujBXnP5UUrYULlg6Pt12yXx/EnHBu8TyfomR9sGXZYo7qPsu3q+dglq9UIFgg8nMAMWch4TDrE8b2k1UBmUZx5HMBcK34q3SF1VuW+kfMcDPMl9vRBf0/8tfp/ajakq/MFWd7h2EUGW6xP7Ot+X9x3C72oVbB2EC/s+u92aUtLVm6pk/DDsuituFtetU1FQEPNEXqQuDza2WS+Qi3Tq1gTPF7GUUojqIqzmEqNz5AbxHDkflT2A8MM9ROqTaslhJ3RPGXGccHBiC+oqm/+rbAAzjTUrC1chTITV5uHgmx4vI/LsbDMgN0mt9p97ZSKwZsIkXC2igku1Q0YXRvAgMBAAECggEAJ33LRe7aHDVuUUMRryKr5tkVaYfz7UINucJZjcKVrrBVAqS409zc7fU1lDBpYLZ0rTQZMFmUAbEiqzTRRASVOzlmBOQTfJfwZ4aVoQJhxIMZpq/qoU35ljhH3sdLhZycEF2jkMXjnUpC8fwpZo71ZdQ2x4/ZTa8H5FJp+xsEpKXcKeI6yScxnJ5O6tpR/2lqTlbB0wzp7Iu9OCYRCwUzWmW87VgG25DJ1eyuxa05OaOqlVy0tS/PAQDVVVCh8BomqgBNW/VVABv3Z6quhP2gJDkCwGElOFmTwbxpEiQ+ePFhGhIFnKFQRrq4NnwJFJItvSoP36TEQsTut9n7+tyXAQKBgQD1A8RQGwzbJ5DNubJkYd2IaoZj+5u3VmKoQNzl6D4rR1w1zHtwYT18XWzyWf6OdC8UhuuYfM6lbl5w8qDkQi6rarv9CR0NJ6cP2G6jHB2+BU6+Ja4LGXDLOmZxuA7ZvF+wXlowkRnib80JSjxvnSkYTj3GQ6FPe9YigaxEdOaCLwKBgQDohKnezTV1wZMiNFwIm4rFpIp4wsulvwbhOV/DTtipO8xx9mlLfRi6EuEh1IKKfhoIJ9qB/tw9vAIKcJw+Q2s07DQrye5JqLO/82vnH60tjGvOfDj3zsa7MEn1EXKsYL4VdAsTJ3rJpW7zLuXdRkksZ1ZmutNgj84l2GaKgzLhwQKBgFZPA2JshPTWVS4DEhJGXzFkxP6HbW0B4zL91lKuoue/9X2GEJ2fw3cBuhUNGpy31LXYaTmIDYs8+8uxzHdb0PDVYm9aPH+bzj/IsACJMPj1Ca31u/9w8MjGQ7wfaCvPLa4FLqQZGRMo6wMwwWVX6VgEh8JFpJdJOj9hint66pBFAoGAZeKDwNIwo7m/rBQ/Y7IsW7Be0M2iiK0s6ZHHaYBqJbXDPwiXWPGm3RoatkU1MlRROdOkxqOThCWWy1ZO0GWgW19I+QsRtAsNQIX8eRkDPFs0fhUmrUdZA3sEXTNZCTmW8TWZCLqa7jLkbADXzl7W/3MEhB1HNB+vWBv7yqP0rsECgYEAwprL9hNIdN/ggAthffSsGF3GguW6GEIBdytw+w8IGDg/EuhmwVO1N4f2VCz5LJLe2yHreyAlN5GK0AnsMCc4yrnIGtqZnyJb/jgXDnAXVxHRxxCMuuVVgnrrbg3AzkOWT5UewW68H4okCt+hURw46EiNcyTU2qC1fYoHk8807Ko=
    alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgwkishq9iUPJMp8LG/+rYPCf0zM3qYgePvSZiluzlvlKXEeJMhntM+iI0kUwXdtbHs5MDg6nFQ0aVFINzyGVy2vcoyk4aAeUrevjXEEHbSLi7p/ho/44jTGS9QxWv0mPgbyYSpjqCwyZAAJyBoL/6sTaAJRxDUbhC2BZKESCIoOiomZw4c8myR0buBkt6rua+u/kI2LQuSwHohqyoRRVZTxkDkRCHTDpNnZAc5uOQnBkJgZaq+f2855xQy4ooNpjCQWh6s+Z6TUDJLPGzenZTmRFCeMV0ZIeuvelS/OZtt9bvHuzGFWPjeH5MOYOqbdGnUk5mNrExT6AgOEkqNYP4wIDAQAB

