name: nakama-node-jp1

database:
  address:
    - "postgres://nakama:nakama@localhost:5432/nakama?sslmode=disable"
  max_open_conns: 30
  max_idle_conns: 10
logger:
  level: "debug"

session:
  encryption_key: "defaultencryptionkey"
  token_expiry_sec: 86400
  refresh_encryption_key: "defaultrefreshencryptionkey"
  refresh_token_expiry_sec: 186400
  single_socket: true
  single_session: true

#cluster:
#  enabled: true
#  redis_address: "localhost:6379"
#  redis_password: ""
#  redis_db: 0

socket:
  server_key: "sparkgame"
  port: 7350

console:
  port: 7351
  username: "admin"
  password: "password"
