name: nakama-node-jp2

database:
  address:
    - "root:sparkinfi123!@192.168.102.223:5432?dbname=test"
  max_open_conns: 30
  max_idle_conns: 10
logger:
  level: "debug"

session:
  encryption_key: "defaultencryptionkey"
  token_expiry_sec: 86400
  refresh_encryption_key: "defaultrefreshencryptionkey"
  refresh_token_expiry_sec: 186400
  single_socket: true
  single_session: true

cluster:
  enabled: true
  redis_address: "192.168.102.223:6379"
  redis_password: ""
  redis_db: 0

socket:
  server_key: "sparkgame"
  port: 7450

console:
  port: 7451
  username: "admin"
  password: "password"
