name: nakama-node-jp1

database:
  address:
    - "root@192.168.102.223:26257/test"
logger:
  level: "debug"

session:
  encryption_key: "defaultencryptionkey"
  token_expiry_sec: 86400
  refresh_encryption_key: "defaultrefreshencryptionkey"
  refresh_token_expiry_sec: 186400
  single_socket: true
  single_session: true

cluster:
  enabled: true
  redis_address: "192.168.102.223:6379"
  redis_password: ""

socket:
  server_key: "sparkgame"
  port: 7350

console:
  port: 7351
  username: "admin"
  password: "password"
