// Copyright 2018 The Nakama Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//*
// The Nakama server RPC protocol for games and apps.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: apigrpc.proto

package apigrpc

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	api "github.com/heroiclabs/nakama-common/api"
	game "github.com/heroiclabs/nakama/v3/game"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_apigrpc_proto protoreflect.FileDescriptor

const file_apigrpc_proto_rawDesc = "" +
	"\n" +
	"\rapigrpc.proto\x12\n" +
	"nakama.api\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a1github.com/heroiclabs/nakama-common/api/api.proto\x1a\tmsg.proto2\xe9~\n" +
	"\x06Nakama\x12W\n" +
	"\n" +
	"AddFriends\x12\x1d.nakama.api.AddFriendsRequest\x1a\x16.google.protobuf.Empty\"\x12\x82\xd3\xe4\x93\x02\f\"\n" +
	"/v2/friend\x12k\n" +
	"\rAddGroupUsers\x12 .nakama.api.AddGroupUsersRequest\x1a\x16.google.protobuf.Empty\" \x82\xd3\xe4\x93\x02\x1a\"\x18/v2/group/{group_id}/add\x12\x84\x01\n" +
	"\x0eSessionRefresh\x12!.nakama.api.SessionRefreshRequest\x1a\x13.nakama.api.Session\":\x92A\x11b\x0f\n" +
	"\r\n" +
	"\tBasicAuth\x12\x00\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v2/account/session/refresh\x12h\n" +
	"\rSessionLogout\x12 .nakama.api.SessionLogoutRequest\x1a\x16.google.protobuf.Empty\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v2/session/logout\x12\x93\x01\n" +
	"\x11AuthenticateApple\x12$.nakama.api.AuthenticateAppleRequest\x1a\x13.nakama.api.Session\"C\x92A\x11b\x0f\n" +
	"\r\n" +
	"\tBasicAuth\x12\x00\x82\xd3\xe4\x93\x02):\aaccount\"\x1e/v2/account/authenticate/apple\x12\x96\x01\n" +
	"\x12AuthenticateCustom\x12%.nakama.api.AuthenticateCustomRequest\x1a\x13.nakama.api.Session\"D\x92A\x11b\x0f\n" +
	"\r\n" +
	"\tBasicAuth\x12\x00\x82\xd3\xe4\x93\x02*:\aaccount\"\x1f/v2/account/authenticate/custom\x12\x96\x01\n" +
	"\x12AuthenticateDevice\x12%.nakama.api.AuthenticateDeviceRequest\x1a\x13.nakama.api.Session\"D\x92A\x11b\x0f\n" +
	"\r\n" +
	"\tBasicAuth\x12\x00\x82\xd3\xe4\x93\x02*:\aaccount\"\x1f/v2/account/authenticate/device\x12\x93\x01\n" +
	"\x11AuthenticateEmail\x12$.nakama.api.AuthenticateEmailRequest\x1a\x13.nakama.api.Session\"C\x92A\x11b\x0f\n" +
	"\r\n" +
	"\tBasicAuth\x12\x00\x82\xd3\xe4\x93\x02):\aaccount\"\x1e/v2/account/authenticate/email\x12\x9c\x01\n" +
	"\x14AuthenticateFacebook\x12'.nakama.api.AuthenticateFacebookRequest\x1a\x13.nakama.api.Session\"F\x92A\x11b\x0f\n" +
	"\r\n" +
	"\tBasicAuth\x12\x00\x82\xd3\xe4\x93\x02,:\aaccount\"!/v2/account/authenticate/facebook\x12\xbd\x01\n" +
	"\x1fAuthenticateFacebookInstantGame\x122.nakama.api.AuthenticateFacebookInstantGameRequest\x1a\x13.nakama.api.Session\"Q\x92A\x11b\x0f\n" +
	"\r\n" +
	"\tBasicAuth\x12\x00\x82\xd3\xe4\x93\x027:\aaccount\",/v2/account/authenticate/facebookinstantgame\x12\xa2\x01\n" +
	"\x16AuthenticateGameCenter\x12).nakama.api.AuthenticateGameCenterRequest\x1a\x13.nakama.api.Session\"H\x92A\x11b\x0f\n" +
	"\r\n" +
	"\tBasicAuth\x12\x00\x82\xd3\xe4\x93\x02.:\aaccount\"#/v2/account/authenticate/gamecenter\x12\x96\x01\n" +
	"\x12AuthenticateGoogle\x12%.nakama.api.AuthenticateGoogleRequest\x1a\x13.nakama.api.Session\"D\x92A\x11b\x0f\n" +
	"\r\n" +
	"\tBasicAuth\x12\x00\x82\xd3\xe4\x93\x02*:\aaccount\"\x1f/v2/account/authenticate/google\x12\x93\x01\n" +
	"\x11AuthenticateSteam\x12$.nakama.api.AuthenticateSteamRequest\x1a\x13.nakama.api.Session\"C\x92A\x11b\x0f\n" +
	"\r\n" +
	"\tBasicAuth\x12\x00\x82\xd3\xe4\x93\x02):\aaccount\"\x1e/v2/account/authenticate/steam\x12k\n" +
	"\rBanGroupUsers\x12 .nakama.api.BanGroupUsersRequest\x1a\x16.google.protobuf.Empty\" \x82\xd3\xe4\x93\x02\x1a\"\x18/v2/group/{group_id}/ban\x12a\n" +
	"\fBlockFriends\x12\x1f.nakama.api.BlockFriendsRequest\x1a\x16.google.protobuf.Empty\"\x18\x82\xd3\xe4\x93\x02\x12\"\x10/v2/friend/block\x12V\n" +
	"\vCreateGroup\x12\x1e.nakama.api.CreateGroupRequest\x1a\x11.nakama.api.Group\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v2/group\x12T\n" +
	"\rDeleteAccount\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x13\x82\xd3\xe4\x93\x02\r*\v/v2/account\x12]\n" +
	"\rDeleteFriends\x12 .nakama.api.DeleteFriendsRequest\x1a\x16.google.protobuf.Empty\"\x12\x82\xd3\xe4\x93\x02\f*\n" +
	"/v2/friend\x12c\n" +
	"\vDeleteGroup\x12\x1e.nakama.api.DeleteGroupRequest\x1a\x16.google.protobuf.Empty\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/v2/group/{group_id}\x12\x87\x01\n" +
	"\x17DeleteLeaderboardRecord\x12*.nakama.api.DeleteLeaderboardRecordRequest\x1a\x16.google.protobuf.Empty\"(\x82\xd3\xe4\x93\x02\"* /v2/leaderboard/{leaderboard_id}\x12o\n" +
	"\x13DeleteNotifications\x12&.nakama.api.DeleteNotificationsRequest\x1a\x16.google.protobuf.Empty\"\x18\x82\xd3\xe4\x93\x02\x12*\x10/v2/notification\x12\x83\x01\n" +
	"\x16DeleteTournamentRecord\x12).nakama.api.DeleteTournamentRecordRequest\x1a\x16.google.protobuf.Empty\"&\x82\xd3\xe4\x93\x02 *\x1e/v2/tournament/{tournament_id}\x12v\n" +
	"\x14DeleteStorageObjects\x12'.nakama.api.DeleteStorageObjectsRequest\x1a\x16.google.protobuf.Empty\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/v2/storage/delete\x12H\n" +
	"\x05Event\x12\x11.nakama.api.Event\x1a\x16.google.protobuf.Empty\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v2/event\x12N\n" +
	"\n" +
	"GetAccount\x12\x16.google.protobuf.Empty\x1a\x13.nakama.api.Account\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v2/account\x12L\n" +
	"\bGetUsers\x12\x1b.nakama.api.GetUsersRequest\x1a\x11.nakama.api.Users\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v2/user\x12\x83\x01\n" +
	"\x0fGetSubscription\x12\".nakama.api.GetSubscriptionRequest\x1a!.nakama.api.ValidatedSubscription\")\x82\xd3\xe4\x93\x02#\x12!/v2/iap/subscription/{product_id}\x12g\n" +
	"\x12GetMatchmakerStats\x12\x16.google.protobuf.Empty\x1a\x1b.nakama.api.MatchmakerStats\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v2/matchmaker/stats\x12S\n" +
	"\vHealthcheck\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/healthcheck\x12\x7f\n" +
	"\x15ImportFacebookFriends\x12(.nakama.api.ImportFacebookFriendsRequest\x1a\x16.google.protobuf.Empty\"$\x82\xd3\xe4\x93\x02\x1e:\aaccount\"\x13/v2/friend/facebook\x12v\n" +
	"\x12ImportSteamFriends\x12%.nakama.api.ImportSteamFriendsRequest\x1a\x16.google.protobuf.Empty\"!\x82\xd3\xe4\x93\x02\x1b:\aaccount\"\x10/v2/friend/steam\x12d\n" +
	"\tJoinGroup\x12\x1c.nakama.api.JoinGroupRequest\x1a\x16.google.protobuf.Empty\"!\x82\xd3\xe4\x93\x02\x1b\"\x19/v2/group/{group_id}/join\x12x\n" +
	"\x0eJoinTournament\x12!.nakama.api.JoinTournamentRequest\x1a\x16.google.protobuf.Empty\"+\x82\xd3\xe4\x93\x02%\"#/v2/tournament/{tournament_id}/join\x12n\n" +
	"\x0eKickGroupUsers\x12!.nakama.api.KickGroupUsersRequest\x1a\x16.google.protobuf.Empty\"!\x82\xd3\xe4\x93\x02\x1b\"\x19/v2/group/{group_id}/kick\x12g\n" +
	"\n" +
	"LeaveGroup\x12\x1d.nakama.api.LeaveGroupRequest\x1a\x16.google.protobuf.Empty\"\"\x82\xd3\xe4\x93\x02\x1c\"\x1a/v2/group/{group_id}/leave\x12`\n" +
	"\tLinkApple\x12\x18.nakama.api.AccountApple\x1a\x16.google.protobuf.Empty\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v2/account/link/apple\x12c\n" +
	"\n" +
	"LinkCustom\x12\x19.nakama.api.AccountCustom\x1a\x16.google.protobuf.Empty\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v2/account/link/custom\x12c\n" +
	"\n" +
	"LinkDevice\x12\x19.nakama.api.AccountDevice\x1a\x16.google.protobuf.Empty\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v2/account/link/device\x12`\n" +
	"\tLinkEmail\x12\x18.nakama.api.AccountEmail\x1a\x16.google.protobuf.Empty\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v2/account/link/email\x12s\n" +
	"\fLinkFacebook\x12\x1f.nakama.api.LinkFacebookRequest\x1a\x16.google.protobuf.Empty\"*\x82\xd3\xe4\x93\x02$:\aaccount\"\x19/v2/account/link/facebook\x12\x8a\x01\n" +
	"\x17LinkFacebookInstantGame\x12&.nakama.api.AccountFacebookInstantGame\x1a\x16.google.protobuf.Empty\"/\x82\xd3\xe4\x93\x02):\x01*\"$/v2/account/link/facebookinstantgame\x12o\n" +
	"\x0eLinkGameCenter\x12\x1d.nakama.api.AccountGameCenter\x1a\x16.google.protobuf.Empty\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v2/account/link/gamecenter\x12c\n" +
	"\n" +
	"LinkGoogle\x12\x19.nakama.api.AccountGoogle\x1a\x16.google.protobuf.Empty\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v2/account/link/google\x12d\n" +
	"\tLinkSteam\x12\x1c.nakama.api.LinkSteamRequest\x1a\x16.google.protobuf.Empty\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v2/account/link/steam\x12\x7f\n" +
	"\x13ListChannelMessages\x12&.nakama.api.ListChannelMessagesRequest\x1a\x1e.nakama.api.ChannelMessageList\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v2/channel/{channel_id}\x12Y\n" +
	"\vListFriends\x12\x1e.nakama.api.ListFriendsRequest\x1a\x16.nakama.api.FriendList\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v2/friend\x12}\n" +
	"\x14ListFriendsOfFriends\x12'.nakama.api.ListFriendsOfFriendsRequest\x1a .nakama.api.FriendsOfFriendsList\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v2/friend/friends\x12U\n" +
	"\n" +
	"ListGroups\x12\x1d.nakama.api.ListGroupsRequest\x1a\x15.nakama.api.GroupList\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v2/group\x12q\n" +
	"\x0eListGroupUsers\x12!.nakama.api.ListGroupUsersRequest\x1a\x19.nakama.api.GroupUserList\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v2/group/{group_id}/user\x12\x90\x01\n" +
	"\x16ListLeaderboardRecords\x12).nakama.api.ListLeaderboardRecordsRequest\x1a!.nakama.api.LeaderboardRecordList\"(\x82\xd3\xe4\x93\x02\"\x12 /v2/leaderboard/{leaderboard_id}\x12\xb7\x01\n" +
	"!ListLeaderboardRecordsAroundOwner\x124.nakama.api.ListLeaderboardRecordsAroundOwnerRequest\x1a!.nakama.api.LeaderboardRecordList\"9\x82\xd3\xe4\x93\x023\x121/v2/leaderboard/{leaderboard_id}/owner/{owner_id}\x12W\n" +
	"\vListMatches\x12\x1e.nakama.api.ListMatchesRequest\x1a\x15.nakama.api.MatchList\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v2/match\x12q\n" +
	"\x11ListNotifications\x12$.nakama.api.ListNotificationsRequest\x1a\x1c.nakama.api.NotificationList\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v2/notification\x12\xa2\x01\n" +
	"\x12ListStorageObjects\x12%.nakama.api.ListStorageObjectsRequest\x1a\x1d.nakama.api.StorageObjectList\"F\x82\xd3\xe4\x93\x02@Z$\x12\"/v2/storage/{collection}/{user_id}\x12\x18/v2/storage/{collection}\x12x\n" +
	"\x11ListSubscriptions\x12$.nakama.api.ListSubscriptionsRequest\x1a\x1c.nakama.api.SubscriptionList\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v2/iap/subscription\x12i\n" +
	"\x0fListTournaments\x12\".nakama.api.ListTournamentsRequest\x1a\x1a.nakama.api.TournamentList\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v2/tournament\x12\x8b\x01\n" +
	"\x15ListTournamentRecords\x12(.nakama.api.ListTournamentRecordsRequest\x1a .nakama.api.TournamentRecordList\"&\x82\xd3\xe4\x93\x02 \x12\x1e/v2/tournament/{tournament_id}\x12\xb2\x01\n" +
	" ListTournamentRecordsAroundOwner\x123.nakama.api.ListTournamentRecordsAroundOwnerRequest\x1a .nakama.api.TournamentRecordList\"7\x82\xd3\xe4\x93\x021\x12//v2/tournament/{tournament_id}/owner/{owner_id}\x12p\n" +
	"\x0eListUserGroups\x12!.nakama.api.ListUserGroupsRequest\x1a\x19.nakama.api.UserGroupList\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v2/user/{user_id}/group\x12w\n" +
	"\x11PromoteGroupUsers\x12$.nakama.api.PromoteGroupUsersRequest\x1a\x16.google.protobuf.Empty\"$\x82\xd3\xe4\x93\x02\x1e\"\x1c/v2/group/{group_id}/promote\x12t\n" +
	"\x10DemoteGroupUsers\x12#.nakama.api.DemoteGroupUsersRequest\x1a\x16.google.protobuf.Empty\"#\x82\xd3\xe4\x93\x02\x1d\"\x1b/v2/group/{group_id}/demote\x12o\n" +
	"\x12ReadStorageObjects\x12%.nakama.api.ReadStorageObjectsRequest\x1a\x1a.nakama.api.StorageObjects\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v2/storage\x12\x7f\n" +
	"\aRpcFunc\x12\x0f.nakama.api.Rpc\x1a\x0f.nakama.api.Rpc\"R\x92A\"b \n" +
	"\r\n" +
	"\tBearerJwt\x12\x00\n" +
	"\x0f\n" +
	"\vHttpKeyAuth\x12\x00\x82\xd3\xe4\x93\x02':\apayloadZ\x0e\x12\f/v2/rpc/{id}\"\f/v2/rpc/{id}\x12d\n" +
	"\vUnlinkApple\x12\x18.nakama.api.AccountApple\x1a\x16.google.protobuf.Empty\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v2/account/unlink/apple\x12g\n" +
	"\fUnlinkCustom\x12\x19.nakama.api.AccountCustom\x1a\x16.google.protobuf.Empty\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v2/account/unlink/custom\x12g\n" +
	"\fUnlinkDevice\x12\x19.nakama.api.AccountDevice\x1a\x16.google.protobuf.Empty\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v2/account/unlink/device\x12d\n" +
	"\vUnlinkEmail\x12\x18.nakama.api.AccountEmail\x1a\x16.google.protobuf.Empty\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v2/account/unlink/email\x12m\n" +
	"\x0eUnlinkFacebook\x12\x1b.nakama.api.AccountFacebook\x1a\x16.google.protobuf.Empty\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v2/account/unlink/facebook\x12\x8e\x01\n" +
	"\x19UnlinkFacebookInstantGame\x12&.nakama.api.AccountFacebookInstantGame\x1a\x16.google.protobuf.Empty\"1\x82\xd3\xe4\x93\x02+:\x01*\"&/v2/account/unlink/facebookinstantgame\x12s\n" +
	"\x10UnlinkGameCenter\x12\x1d.nakama.api.AccountGameCenter\x1a\x16.google.protobuf.Empty\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v2/account/unlink/gamecenter\x12g\n" +
	"\fUnlinkGoogle\x12\x19.nakama.api.AccountGoogle\x1a\x16.google.protobuf.Empty\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v2/account/unlink/google\x12d\n" +
	"\vUnlinkSteam\x12\x18.nakama.api.AccountSteam\x1a\x16.google.protobuf.Empty\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v2/account/unlink/steam\x12a\n" +
	"\rUpdateAccount\x12 .nakama.api.UpdateAccountRequest\x1a\x16.google.protobuf.Empty\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\x1a\v/v2/account\x12f\n" +
	"\vUpdateGroup\x12\x1e.nakama.api.UpdateGroupRequest\x1a\x16.google.protobuf.Empty\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\x1a\x14/v2/group/{group_id}\x12\x8a\x01\n" +
	"\x15ValidatePurchaseApple\x12(.nakama.api.ValidatePurchaseAppleRequest\x1a$.nakama.api.ValidatePurchaseResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v2/iap/purchase/apple\x12\x9a\x01\n" +
	"\x19ValidateSubscriptionApple\x12,.nakama.api.ValidateSubscriptionAppleRequest\x1a(.nakama.api.ValidateSubscriptionResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v2/iap/subscription/apple\x12\x8d\x01\n" +
	"\x16ValidatePurchaseGoogle\x12).nakama.api.ValidatePurchaseGoogleRequest\x1a$.nakama.api.ValidatePurchaseResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v2/iap/purchase/google\x12\x9d\x01\n" +
	"\x1aValidateSubscriptionGoogle\x12-.nakama.api.ValidateSubscriptionGoogleRequest\x1a(.nakama.api.ValidateSubscriptionResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v2/iap/subscription/google\x12\x8d\x01\n" +
	"\x16ValidatePurchaseHuawei\x12).nakama.api.ValidatePurchaseHuaweiRequest\x1a$.nakama.api.ValidatePurchaseResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v2/iap/purchase/huawei\x12\xa8\x01\n" +
	"\x1fValidatePurchaseFacebookInstant\x122.nakama.api.ValidatePurchaseFacebookInstantRequest\x1a$.nakama.api.ValidatePurchaseResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /v2/iap/purchase/facebookinstant\x12\x94\x01\n" +
	"\x16WriteLeaderboardRecord\x12).nakama.api.WriteLeaderboardRecordRequest\x1a\x1d.nakama.api.LeaderboardRecord\"0\x82\xd3\xe4\x93\x02*:\x06record\" /v2/leaderboard/{leaderboard_id}\x12t\n" +
	"\x13WriteStorageObjects\x12&.nakama.api.WriteStorageObjectsRequest\x1a\x1d.nakama.api.StorageObjectAcks\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\x1a\v/v2/storage\x12\xba\x01\n" +
	"\x15WriteTournamentRecord\x12(.nakama.api.WriteTournamentRecordRequest\x1a\x1d.nakama.api.LeaderboardRecord\"X\x82\xd3\xe4\x93\x02R:\x06recordZ(:\x06record\"\x1e/v2/tournament/{tournament_id}\x1a\x1e/v2/tournament/{tournament_id}\x12`\n" +
	"\n" +
	"RedeemGift\x12\x17.game.RedeemGiftRequest\x1a\x18.game.RedeemGiftResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v2/game/redeem_gift\x12W\n" +
	"\bFeedback\x12\x15.game.FeedbackRequest\x1a\x16.google.protobuf.Empty\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v2/game/feedback\x12\x87\x01\n" +
	"\x12AuthenticateWechat\x12\x1f.game.AuthenticateWechatRequest\x1a\x13.nakama.api.Session\";\x92A\x11b\x0f\n" +
	"\r\n" +
	"\tBasicAuth\x12\x00\x82\xd3\xe4\x93\x02!\"\x1f/v2/account/authenticate/wechat\x12\x87\x01\n" +
	"\x12AuthenticateTikTok\x12\x1f.game.AuthenticateTiktokRequest\x1a\x13.nakama.api.Session\";\x92A\x11b\x0f\n" +
	"\r\n" +
	"\tBasicAuth\x12\x00\x82\xd3\xe4\x93\x02!\"\x1f/v2/account/authenticate/tiktok\x12e\n" +
	"\x0fSubmitBeInvited\x12\x1c.game.SubmitBeInvitedRequest\x1a\x16.google.protobuf.Empty\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v2/invite/submit\x12Z\n" +
	"\vListInvitee\x12\x16.google.protobuf.Empty\x1a\x19.game.ListInviteeResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v2/invitee/list\x12q\n" +
	"\x11ClaimInviteReward\x12\x1e.game.ClaimInviteRewardRequest\x1a\x1f.game.ClaimInviteRewardResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v2/invite/claim\x12p\n" +
	"\x0fClaimByteReward\x12\x1c.game.ClaimByteRewardRequest\x1a\x1d.game.ClaimByteRewardResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v2/byte/reward/claim\x12W\n" +
	"\vGetGameTime\x12\x16.google.protobuf.Empty\x1a\x19.game.GetGameTimeResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v2/game/time\x12\x8f\x01\n" +
	"\x1aListPublishedAnnouncements\x12'.game.ListPublishedAnnouncementsRequest\x1a(.game.ListPublishedAnnouncementsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v2/game/announcements\x12\x82\x01\n" +
	"\x15MarkNotificationsRead\x12\".game.MarkNotificationsReadRequest\x1a#.game.MarkNotificationsReadResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v2/notification/read\x12\x98\x01\n" +
	"\x1cClaimNotificationAttachments\x12).game.ClaimNotificationAttachmentsRequest\x1a*.game.ClaimNotificationAttachmentsResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v2/notification/claim\x12X\n" +
	"\x11GetCurrentStamina\x12\x16.google.protobuf.Empty\x1a\x11.game.StaminaData\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v2/game/stamina\x12O\n" +
	"\fGetEquipData\x12\x16.google.protobuf.Empty\x1a\x0f.game.EquipData\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v2/game/equip\x12l\n" +
	"\rOperateWallet\x12\x1a.game.OperateWalletRequest\x1a\x1b.game.OperateWalletResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v2/game/wallet/operate\x12a\n" +
	"\rGetWalletData\x12\x1a.game.GetWalletDataRequest\x1a\x1b.game.GetWalletDataResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v2/game/wallet\x12x\n" +
	"\x10OperateInventory\x12\x1d.game.OperateInventoryRequest\x1a\x1e.game.OperateInventoryResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v2/game/inventory/operate\x12m\n" +
	"\x10GetInventoryData\x12\x1d.game.GetInventoryDataRequest\x1a\x1e.game.GetInventoryDataResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v2/game/inventory\x12L\n" +
	"\vGetShopData\x12\x16.google.protobuf.Empty\x1a\x0e.game.ShopData\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v2/game/shop\x12`\n" +
	"\vBuyShopItem\x12\x18.game.BuyShopItemRequest\x1a\x19.game.BuyShopItemResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v2/game/shop/buy\x12d\n" +
	"\vRefreshShop\x12\x18.game.RefreshShopRequest\x1a\x19.game.RefreshShopResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v2/game/shop/refresh\x12R\n" +
	"\n" +
	"GetBoxShop\x12\x16.google.protobuf.Empty\x1a\x11.game.BoxShopData\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v2/game/shop/box\x12a\n" +
	"\n" +
	"BuyBoxItem\x12\x17.game.BuyBoxItemRequest\x1a\x18.game.BuyBoxItemResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v2/game/shop/box/buy\x12^\n" +
	"\x0eGetChapterShop\x12\x16.google.protobuf.Empty\x1a\x15.game.ChapterShopData\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v2/game/shop/chapter\x12y\n" +
	"\x10ClaimChapterItem\x12\x1d.game.ClaimChapterItemRequest\x1a\x1e.game.ClaimChapterItemResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v2/game/shop/chapter/claim\x12R\n" +
	"\n" +
	"GetGemShop\x12\x16.google.protobuf.Empty\x1a\x11.game.GemShopData\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v2/game/shop/gem\x12i\n" +
	"\fClaimGemItem\x12\x19.game.ClaimGemItemRequest\x1a\x1a.game.ClaimGemItemResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v2/game/shop/gem/claim\x12\\\n" +
	"\tEndBattle\x12\x16.game.EndBattleRequest\x1a\x17.game.EndBattleResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v2/game/battle/end\x12d\n" +
	"\vStartBattle\x12\x18.game.StartBattleRequest\x1a\x19.game.StartBattleResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v2/game/battle/start\x12\x92\x01\n" +
	"\x18ClaimBattleRewardByShare\x12%.game.ClaimBattleRewardByShareRequest\x1a&.game.ClaimBattleRewardByShareResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v2/game/battle/reward/share\x12z\n" +
	"\x12ClaimMoppingReward\x12\x1f.game.ClaimMoppingRewardRequest\x1a .game.ClaimMoppingRewardResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v2/game/mopping/claim\x12v\n" +
	"\x11ClaimOnHookReward\x12\x1e.game.ClaimOnHookRewardRequest\x1a\x1f.game.ClaimOnHookRewardResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v2/game/onhook/claim\x12h\n" +
	"\fUpgradeEquip\x12\x19.game.UpgradeEquipRequest\x1a\x1a.game.UpgradeEquipResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v2/game/equip/upgrade\x12\x86\x01\n" +
	"\x12UpgradeCrystalTech\x12\x1f.game.UpgradeCrystalTechRequest\x1a .game.UpgradeCrystalTechResponse\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/v2/game/equip/crystaltech/upgrade\x12m\n" +
	"\rClaimLevelBox\x12\x1a.game.ClaimLevelBoxRequest\x1a\x1b.game.ClaimLevelBoxResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v2/game/level/box/claim\x12e\n" +
	"\vGetLevelBox\x12\x18.game.GetLevelBoxRequest\x1a\x19.game.GetLevelBoxResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v2/game/level/box/get\x12v\n" +
	"\x11ClaimSignInReward\x12\x1e.game.ClaimSignInRewardRequest\x1a\x1f.game.ClaimSignInRewardResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v2/game/signin/claim\x12a\n" +
	"\x0fGetSignInReward\x12\x16.google.protobuf.Empty\x1a\x1d.game.GetSignInRewardResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v2/game/signin\x12\x82\x01\n" +
	"\x14GetFirstChargeStatus\x12!.game.GetFirstChargeStatusRequest\x1a\".game.GetFirstChargeStatusResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v2/game/firstcharge/status\x12\x8a\x01\n" +
	"\x16ClaimFirstChargeReward\x12#.game.ClaimFirstChargeRewardRequest\x1a$.game.ClaimFirstChargeRewardResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v2/game/firstcharge/claim\x12M\n" +
	"\aGetTask\x12\x14.game.GetTaskRequest\x1a\x15.game.GetTaskResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v2/game/task\x12n\n" +
	"\x0fClaimTaskReward\x12\x1c.game.ClaimTaskRewardRequest\x1a\x1d.game.ClaimTaskRewardResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v2/game/task/claim\x12\x83\x01\n" +
	"\x13ClaimLivenessReward\x12 .game.ClaimLivenessRewardRequest\x1a!.game.ClaimLivenessRewardResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v2/game/task/liveness/claim\x12o\n" +
	"\x0eClaimVipReward\x12\x1b.game.ClaimVipRewardRequest\x1a\x1c.game.ClaimVipRewardResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v2/game/activity/claim\x12h\n" +
	"\x0eCheckVipStatus\x12\x16.google.protobuf.Empty\x1a\x1c.game.CheckVipStatusResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v2/game/activity/status\x12v\n" +
	"\x11GetSevenDayStatus\x12\x1e.game.GetSevenDayStatusRequest\x1a\x1f.game.GetSevenDayStatusResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v2/game/sevenday/status\x12~\n" +
	"\x13ClaimSevenDayReward\x12 .game.ClaimSevenDayRewardRequest\x1a!.game.ClaimSevenDayRewardResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v2/game/sevenday/claim\x12_\n" +
	"\fGetChallenge\x12\x16.google.protobuf.Empty\x1a\x1a.game.GetChallengeResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v2/game/challenges\x12m\n" +
	"\rJoinChallenge\x12\x1a.game.JoinChallengeRequest\x1a\x1b.game.JoinChallengeResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v2/game/challenges/join\x12\x7f\n" +
	"\x13GainChallengeReward\x12 .game.GainChallengeRewardRequest\x1a!.game.GainChallengeRewardResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v2/game/challenges/gain\x12\x7f\n" +
	"\x14GetChallengeTopStats\x12\x16.google.protobuf.Empty\x1a\".game.GetChallengeTopStatsResponse\"+\x82\xd3\xe4\x93\x02%\x12#/v2/game/challenges/top-three-stats\x12\x90\x01\n" +
	"\x17GetChallengeBattleTimes\x12$.game.GetChallengeBattleTimesRequest\x1a%.game.GetChallengeBattleTimesResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /v2/game/challenges/battle-times\x12\x97\x01\n" +
	"\x17BuyChallengeBattleTimes\x12$.game.BuyChallengeBattleTimesRequest\x1a%.game.BuyChallengeBattleTimesResponse\"/\x82\xd3\xe4\x93\x02):\x01*\"$/v2/game/challenges/battle-times/buy\x12`\n" +
	"\fPurchaseTest\x12\x15.game.PurchaseRequest\x1a\x16.game.PurchaseResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v2/game/purchase/testB\xba\x03\x92A\xcf\x02\x12u\n" +
	"\rNakama API v2\"_\n" +
	"!The Nakama Authors & Contributors\x12$https://github.com/heroiclabs/nakama\x1a\x14hello@heroiclabs.com2\x032.0\x1a\x0e127.0.0.1:7350*\x01\x012\x10application/json:\x10application/jsonZR\n" +
	"\x0f\n" +
	"\tBasicAuth\x12\x02\b\x01\n" +
	" \n" +
	"\tBearerJwt\x12\x13\b\x02\x1a\rAuthorization \x02\n" +
	"\x1d\n" +
	"\vHttpKeyAuth\x12\x0e\b\x02\x1a\bhttp_key \x02b\x0f\n" +
	"\r\n" +
	"\tBearerJwt\x12\x00r:\n" +
	"\x1bNakama server documentation\x12\x1bhttps://heroiclabs.com/docs\n" +
	"\x19com.heroiclabs.nakama.apiB\rNakamaApiGrpcP\x01Z'github.com/heroiclabs/nakama/v3/apigrpc\xaa\x02\x0fNakama.Protobufb\x06proto3"

var file_apigrpc_proto_goTypes = []any{
	(*api.AddFriendsRequest)(nil),                        // 0: nakama.api.AddFriendsRequest
	(*api.AddGroupUsersRequest)(nil),                     // 1: nakama.api.AddGroupUsersRequest
	(*api.SessionRefreshRequest)(nil),                    // 2: nakama.api.SessionRefreshRequest
	(*api.SessionLogoutRequest)(nil),                     // 3: nakama.api.SessionLogoutRequest
	(*api.AuthenticateAppleRequest)(nil),                 // 4: nakama.api.AuthenticateAppleRequest
	(*api.AuthenticateCustomRequest)(nil),                // 5: nakama.api.AuthenticateCustomRequest
	(*api.AuthenticateDeviceRequest)(nil),                // 6: nakama.api.AuthenticateDeviceRequest
	(*api.AuthenticateEmailRequest)(nil),                 // 7: nakama.api.AuthenticateEmailRequest
	(*api.AuthenticateFacebookRequest)(nil),              // 8: nakama.api.AuthenticateFacebookRequest
	(*api.AuthenticateFacebookInstantGameRequest)(nil),   // 9: nakama.api.AuthenticateFacebookInstantGameRequest
	(*api.AuthenticateGameCenterRequest)(nil),            // 10: nakama.api.AuthenticateGameCenterRequest
	(*api.AuthenticateGoogleRequest)(nil),                // 11: nakama.api.AuthenticateGoogleRequest
	(*api.AuthenticateSteamRequest)(nil),                 // 12: nakama.api.AuthenticateSteamRequest
	(*api.BanGroupUsersRequest)(nil),                     // 13: nakama.api.BanGroupUsersRequest
	(*api.BlockFriendsRequest)(nil),                      // 14: nakama.api.BlockFriendsRequest
	(*api.CreateGroupRequest)(nil),                       // 15: nakama.api.CreateGroupRequest
	(*emptypb.Empty)(nil),                                // 16: google.protobuf.Empty
	(*api.DeleteFriendsRequest)(nil),                     // 17: nakama.api.DeleteFriendsRequest
	(*api.DeleteGroupRequest)(nil),                       // 18: nakama.api.DeleteGroupRequest
	(*api.DeleteLeaderboardRecordRequest)(nil),           // 19: nakama.api.DeleteLeaderboardRecordRequest
	(*api.DeleteNotificationsRequest)(nil),               // 20: nakama.api.DeleteNotificationsRequest
	(*api.DeleteTournamentRecordRequest)(nil),            // 21: nakama.api.DeleteTournamentRecordRequest
	(*api.DeleteStorageObjectsRequest)(nil),              // 22: nakama.api.DeleteStorageObjectsRequest
	(*api.Event)(nil),                                    // 23: nakama.api.Event
	(*api.GetUsersRequest)(nil),                          // 24: nakama.api.GetUsersRequest
	(*api.GetSubscriptionRequest)(nil),                   // 25: nakama.api.GetSubscriptionRequest
	(*api.ImportFacebookFriendsRequest)(nil),             // 26: nakama.api.ImportFacebookFriendsRequest
	(*api.ImportSteamFriendsRequest)(nil),                // 27: nakama.api.ImportSteamFriendsRequest
	(*api.JoinGroupRequest)(nil),                         // 28: nakama.api.JoinGroupRequest
	(*api.JoinTournamentRequest)(nil),                    // 29: nakama.api.JoinTournamentRequest
	(*api.KickGroupUsersRequest)(nil),                    // 30: nakama.api.KickGroupUsersRequest
	(*api.LeaveGroupRequest)(nil),                        // 31: nakama.api.LeaveGroupRequest
	(*api.AccountApple)(nil),                             // 32: nakama.api.AccountApple
	(*api.AccountCustom)(nil),                            // 33: nakama.api.AccountCustom
	(*api.AccountDevice)(nil),                            // 34: nakama.api.AccountDevice
	(*api.AccountEmail)(nil),                             // 35: nakama.api.AccountEmail
	(*api.LinkFacebookRequest)(nil),                      // 36: nakama.api.LinkFacebookRequest
	(*api.AccountFacebookInstantGame)(nil),               // 37: nakama.api.AccountFacebookInstantGame
	(*api.AccountGameCenter)(nil),                        // 38: nakama.api.AccountGameCenter
	(*api.AccountGoogle)(nil),                            // 39: nakama.api.AccountGoogle
	(*api.LinkSteamRequest)(nil),                         // 40: nakama.api.LinkSteamRequest
	(*api.ListChannelMessagesRequest)(nil),               // 41: nakama.api.ListChannelMessagesRequest
	(*api.ListFriendsRequest)(nil),                       // 42: nakama.api.ListFriendsRequest
	(*api.ListFriendsOfFriendsRequest)(nil),              // 43: nakama.api.ListFriendsOfFriendsRequest
	(*api.ListGroupsRequest)(nil),                        // 44: nakama.api.ListGroupsRequest
	(*api.ListGroupUsersRequest)(nil),                    // 45: nakama.api.ListGroupUsersRequest
	(*api.ListLeaderboardRecordsRequest)(nil),            // 46: nakama.api.ListLeaderboardRecordsRequest
	(*api.ListLeaderboardRecordsAroundOwnerRequest)(nil), // 47: nakama.api.ListLeaderboardRecordsAroundOwnerRequest
	(*api.ListMatchesRequest)(nil),                       // 48: nakama.api.ListMatchesRequest
	(*api.ListNotificationsRequest)(nil),                 // 49: nakama.api.ListNotificationsRequest
	(*api.ListStorageObjectsRequest)(nil),                // 50: nakama.api.ListStorageObjectsRequest
	(*api.ListSubscriptionsRequest)(nil),                 // 51: nakama.api.ListSubscriptionsRequest
	(*api.ListTournamentsRequest)(nil),                   // 52: nakama.api.ListTournamentsRequest
	(*api.ListTournamentRecordsRequest)(nil),             // 53: nakama.api.ListTournamentRecordsRequest
	(*api.ListTournamentRecordsAroundOwnerRequest)(nil),  // 54: nakama.api.ListTournamentRecordsAroundOwnerRequest
	(*api.ListUserGroupsRequest)(nil),                    // 55: nakama.api.ListUserGroupsRequest
	(*api.PromoteGroupUsersRequest)(nil),                 // 56: nakama.api.PromoteGroupUsersRequest
	(*api.DemoteGroupUsersRequest)(nil),                  // 57: nakama.api.DemoteGroupUsersRequest
	(*api.ReadStorageObjectsRequest)(nil),                // 58: nakama.api.ReadStorageObjectsRequest
	(*api.Rpc)(nil),                                      // 59: nakama.api.Rpc
	(*api.AccountFacebook)(nil),                          // 60: nakama.api.AccountFacebook
	(*api.AccountSteam)(nil),                             // 61: nakama.api.AccountSteam
	(*api.UpdateAccountRequest)(nil),                     // 62: nakama.api.UpdateAccountRequest
	(*api.UpdateGroupRequest)(nil),                       // 63: nakama.api.UpdateGroupRequest
	(*api.ValidatePurchaseAppleRequest)(nil),             // 64: nakama.api.ValidatePurchaseAppleRequest
	(*api.ValidateSubscriptionAppleRequest)(nil),         // 65: nakama.api.ValidateSubscriptionAppleRequest
	(*api.ValidatePurchaseGoogleRequest)(nil),            // 66: nakama.api.ValidatePurchaseGoogleRequest
	(*api.ValidateSubscriptionGoogleRequest)(nil),        // 67: nakama.api.ValidateSubscriptionGoogleRequest
	(*api.ValidatePurchaseHuaweiRequest)(nil),            // 68: nakama.api.ValidatePurchaseHuaweiRequest
	(*api.ValidatePurchaseFacebookInstantRequest)(nil),   // 69: nakama.api.ValidatePurchaseFacebookInstantRequest
	(*api.WriteLeaderboardRecordRequest)(nil),            // 70: nakama.api.WriteLeaderboardRecordRequest
	(*api.WriteStorageObjectsRequest)(nil),               // 71: nakama.api.WriteStorageObjectsRequest
	(*api.WriteTournamentRecordRequest)(nil),             // 72: nakama.api.WriteTournamentRecordRequest
	(*game.RedeemGiftRequest)(nil),                       // 73: game.RedeemGiftRequest
	(*game.FeedbackRequest)(nil),                         // 74: game.FeedbackRequest
	(*game.AuthenticateWechatRequest)(nil),               // 75: game.AuthenticateWechatRequest
	(*game.AuthenticateTiktokRequest)(nil),               // 76: game.AuthenticateTiktokRequest
	(*game.SubmitBeInvitedRequest)(nil),                  // 77: game.SubmitBeInvitedRequest
	(*game.ClaimInviteRewardRequest)(nil),                // 78: game.ClaimInviteRewardRequest
	(*game.ClaimByteRewardRequest)(nil),                  // 79: game.ClaimByteRewardRequest
	(*game.ListPublishedAnnouncementsRequest)(nil),       // 80: game.ListPublishedAnnouncementsRequest
	(*game.MarkNotificationsReadRequest)(nil),            // 81: game.MarkNotificationsReadRequest
	(*game.ClaimNotificationAttachmentsRequest)(nil),     // 82: game.ClaimNotificationAttachmentsRequest
	(*game.OperateWalletRequest)(nil),                    // 83: game.OperateWalletRequest
	(*game.GetWalletDataRequest)(nil),                    // 84: game.GetWalletDataRequest
	(*game.OperateInventoryRequest)(nil),                 // 85: game.OperateInventoryRequest
	(*game.GetInventoryDataRequest)(nil),                 // 86: game.GetInventoryDataRequest
	(*game.BuyShopItemRequest)(nil),                      // 87: game.BuyShopItemRequest
	(*game.RefreshShopRequest)(nil),                      // 88: game.RefreshShopRequest
	(*game.BuyBoxItemRequest)(nil),                       // 89: game.BuyBoxItemRequest
	(*game.ClaimChapterItemRequest)(nil),                 // 90: game.ClaimChapterItemRequest
	(*game.ClaimGemItemRequest)(nil),                     // 91: game.ClaimGemItemRequest
	(*game.EndBattleRequest)(nil),                        // 92: game.EndBattleRequest
	(*game.StartBattleRequest)(nil),                      // 93: game.StartBattleRequest
	(*game.ClaimBattleRewardByShareRequest)(nil),         // 94: game.ClaimBattleRewardByShareRequest
	(*game.ClaimMoppingRewardRequest)(nil),               // 95: game.ClaimMoppingRewardRequest
	(*game.ClaimOnHookRewardRequest)(nil),                // 96: game.ClaimOnHookRewardRequest
	(*game.UpgradeEquipRequest)(nil),                     // 97: game.UpgradeEquipRequest
	(*game.UpgradeCrystalTechRequest)(nil),               // 98: game.UpgradeCrystalTechRequest
	(*game.ClaimLevelBoxRequest)(nil),                    // 99: game.ClaimLevelBoxRequest
	(*game.GetLevelBoxRequest)(nil),                      // 100: game.GetLevelBoxRequest
	(*game.ClaimSignInRewardRequest)(nil),                // 101: game.ClaimSignInRewardRequest
	(*game.GetFirstChargeStatusRequest)(nil),             // 102: game.GetFirstChargeStatusRequest
	(*game.ClaimFirstChargeRewardRequest)(nil),           // 103: game.ClaimFirstChargeRewardRequest
	(*game.GetTaskRequest)(nil),                          // 104: game.GetTaskRequest
	(*game.ClaimTaskRewardRequest)(nil),                  // 105: game.ClaimTaskRewardRequest
	(*game.ClaimLivenessRewardRequest)(nil),              // 106: game.ClaimLivenessRewardRequest
	(*game.ClaimVipRewardRequest)(nil),                   // 107: game.ClaimVipRewardRequest
	(*game.GetSevenDayStatusRequest)(nil),                // 108: game.GetSevenDayStatusRequest
	(*game.ClaimSevenDayRewardRequest)(nil),              // 109: game.ClaimSevenDayRewardRequest
	(*game.JoinChallengeRequest)(nil),                    // 110: game.JoinChallengeRequest
	(*game.GainChallengeRewardRequest)(nil),              // 111: game.GainChallengeRewardRequest
	(*game.GetChallengeBattleTimesRequest)(nil),          // 112: game.GetChallengeBattleTimesRequest
	(*game.BuyChallengeBattleTimesRequest)(nil),          // 113: game.BuyChallengeBattleTimesRequest
	(*game.PurchaseRequest)(nil),                         // 114: game.PurchaseRequest
	(*api.Session)(nil),                                  // 115: nakama.api.Session
	(*api.Group)(nil),                                    // 116: nakama.api.Group
	(*api.Account)(nil),                                  // 117: nakama.api.Account
	(*api.Users)(nil),                                    // 118: nakama.api.Users
	(*api.ValidatedSubscription)(nil),                    // 119: nakama.api.ValidatedSubscription
	(*api.MatchmakerStats)(nil),                          // 120: nakama.api.MatchmakerStats
	(*api.ChannelMessageList)(nil),                       // 121: nakama.api.ChannelMessageList
	(*api.FriendList)(nil),                               // 122: nakama.api.FriendList
	(*api.FriendsOfFriendsList)(nil),                     // 123: nakama.api.FriendsOfFriendsList
	(*api.GroupList)(nil),                                // 124: nakama.api.GroupList
	(*api.GroupUserList)(nil),                            // 125: nakama.api.GroupUserList
	(*api.LeaderboardRecordList)(nil),                    // 126: nakama.api.LeaderboardRecordList
	(*api.MatchList)(nil),                                // 127: nakama.api.MatchList
	(*api.NotificationList)(nil),                         // 128: nakama.api.NotificationList
	(*api.StorageObjectList)(nil),                        // 129: nakama.api.StorageObjectList
	(*api.SubscriptionList)(nil),                         // 130: nakama.api.SubscriptionList
	(*api.TournamentList)(nil),                           // 131: nakama.api.TournamentList
	(*api.TournamentRecordList)(nil),                     // 132: nakama.api.TournamentRecordList
	(*api.UserGroupList)(nil),                            // 133: nakama.api.UserGroupList
	(*api.StorageObjects)(nil),                           // 134: nakama.api.StorageObjects
	(*api.ValidatePurchaseResponse)(nil),                 // 135: nakama.api.ValidatePurchaseResponse
	(*api.ValidateSubscriptionResponse)(nil),             // 136: nakama.api.ValidateSubscriptionResponse
	(*api.LeaderboardRecord)(nil),                        // 137: nakama.api.LeaderboardRecord
	(*api.StorageObjectAcks)(nil),                        // 138: nakama.api.StorageObjectAcks
	(*game.RedeemGiftResponse)(nil),                      // 139: game.RedeemGiftResponse
	(*game.ListInviteeResponse)(nil),                     // 140: game.ListInviteeResponse
	(*game.ClaimInviteRewardResponse)(nil),               // 141: game.ClaimInviteRewardResponse
	(*game.ClaimByteRewardResponse)(nil),                 // 142: game.ClaimByteRewardResponse
	(*game.GetGameTimeResponse)(nil),                     // 143: game.GetGameTimeResponse
	(*game.ListPublishedAnnouncementsResponse)(nil),      // 144: game.ListPublishedAnnouncementsResponse
	(*game.MarkNotificationsReadResponse)(nil),           // 145: game.MarkNotificationsReadResponse
	(*game.ClaimNotificationAttachmentsResponse)(nil),    // 146: game.ClaimNotificationAttachmentsResponse
	(*game.StaminaData)(nil),                             // 147: game.StaminaData
	(*game.EquipData)(nil),                               // 148: game.EquipData
	(*game.OperateWalletResponse)(nil),                   // 149: game.OperateWalletResponse
	(*game.GetWalletDataResponse)(nil),                   // 150: game.GetWalletDataResponse
	(*game.OperateInventoryResponse)(nil),                // 151: game.OperateInventoryResponse
	(*game.GetInventoryDataResponse)(nil),                // 152: game.GetInventoryDataResponse
	(*game.ShopData)(nil),                                // 153: game.ShopData
	(*game.BuyShopItemResponse)(nil),                     // 154: game.BuyShopItemResponse
	(*game.RefreshShopResponse)(nil),                     // 155: game.RefreshShopResponse
	(*game.BoxShopData)(nil),                             // 156: game.BoxShopData
	(*game.BuyBoxItemResponse)(nil),                      // 157: game.BuyBoxItemResponse
	(*game.ChapterShopData)(nil),                         // 158: game.ChapterShopData
	(*game.ClaimChapterItemResponse)(nil),                // 159: game.ClaimChapterItemResponse
	(*game.GemShopData)(nil),                             // 160: game.GemShopData
	(*game.ClaimGemItemResponse)(nil),                    // 161: game.ClaimGemItemResponse
	(*game.EndBattleResponse)(nil),                       // 162: game.EndBattleResponse
	(*game.StartBattleResponse)(nil),                     // 163: game.StartBattleResponse
	(*game.ClaimBattleRewardByShareResponse)(nil),        // 164: game.ClaimBattleRewardByShareResponse
	(*game.ClaimMoppingRewardResponse)(nil),              // 165: game.ClaimMoppingRewardResponse
	(*game.ClaimOnHookRewardResponse)(nil),               // 166: game.ClaimOnHookRewardResponse
	(*game.UpgradeEquipResponse)(nil),                    // 167: game.UpgradeEquipResponse
	(*game.UpgradeCrystalTechResponse)(nil),              // 168: game.UpgradeCrystalTechResponse
	(*game.ClaimLevelBoxResponse)(nil),                   // 169: game.ClaimLevelBoxResponse
	(*game.GetLevelBoxResponse)(nil),                     // 170: game.GetLevelBoxResponse
	(*game.ClaimSignInRewardResponse)(nil),               // 171: game.ClaimSignInRewardResponse
	(*game.GetSignInRewardResponse)(nil),                 // 172: game.GetSignInRewardResponse
	(*game.GetFirstChargeStatusResponse)(nil),            // 173: game.GetFirstChargeStatusResponse
	(*game.ClaimFirstChargeRewardResponse)(nil),          // 174: game.ClaimFirstChargeRewardResponse
	(*game.GetTaskResponse)(nil),                         // 175: game.GetTaskResponse
	(*game.ClaimTaskRewardResponse)(nil),                 // 176: game.ClaimTaskRewardResponse
	(*game.ClaimLivenessRewardResponse)(nil),             // 177: game.ClaimLivenessRewardResponse
	(*game.ClaimVipRewardResponse)(nil),                  // 178: game.ClaimVipRewardResponse
	(*game.CheckVipStatusResponse)(nil),                  // 179: game.CheckVipStatusResponse
	(*game.GetSevenDayStatusResponse)(nil),               // 180: game.GetSevenDayStatusResponse
	(*game.ClaimSevenDayRewardResponse)(nil),             // 181: game.ClaimSevenDayRewardResponse
	(*game.GetChallengeResponse)(nil),                    // 182: game.GetChallengeResponse
	(*game.JoinChallengeResponse)(nil),                   // 183: game.JoinChallengeResponse
	(*game.GainChallengeRewardResponse)(nil),             // 184: game.GainChallengeRewardResponse
	(*game.GetChallengeTopStatsResponse)(nil),            // 185: game.GetChallengeTopStatsResponse
	(*game.GetChallengeBattleTimesResponse)(nil),         // 186: game.GetChallengeBattleTimesResponse
	(*game.BuyChallengeBattleTimesResponse)(nil),         // 187: game.BuyChallengeBattleTimesResponse
	(*game.PurchaseResponse)(nil),                        // 188: game.PurchaseResponse
}
var file_apigrpc_proto_depIdxs = []int32{
	0,   // 0: nakama.api.Nakama.AddFriends:input_type -> nakama.api.AddFriendsRequest
	1,   // 1: nakama.api.Nakama.AddGroupUsers:input_type -> nakama.api.AddGroupUsersRequest
	2,   // 2: nakama.api.Nakama.SessionRefresh:input_type -> nakama.api.SessionRefreshRequest
	3,   // 3: nakama.api.Nakama.SessionLogout:input_type -> nakama.api.SessionLogoutRequest
	4,   // 4: nakama.api.Nakama.AuthenticateApple:input_type -> nakama.api.AuthenticateAppleRequest
	5,   // 5: nakama.api.Nakama.AuthenticateCustom:input_type -> nakama.api.AuthenticateCustomRequest
	6,   // 6: nakama.api.Nakama.AuthenticateDevice:input_type -> nakama.api.AuthenticateDeviceRequest
	7,   // 7: nakama.api.Nakama.AuthenticateEmail:input_type -> nakama.api.AuthenticateEmailRequest
	8,   // 8: nakama.api.Nakama.AuthenticateFacebook:input_type -> nakama.api.AuthenticateFacebookRequest
	9,   // 9: nakama.api.Nakama.AuthenticateFacebookInstantGame:input_type -> nakama.api.AuthenticateFacebookInstantGameRequest
	10,  // 10: nakama.api.Nakama.AuthenticateGameCenter:input_type -> nakama.api.AuthenticateGameCenterRequest
	11,  // 11: nakama.api.Nakama.AuthenticateGoogle:input_type -> nakama.api.AuthenticateGoogleRequest
	12,  // 12: nakama.api.Nakama.AuthenticateSteam:input_type -> nakama.api.AuthenticateSteamRequest
	13,  // 13: nakama.api.Nakama.BanGroupUsers:input_type -> nakama.api.BanGroupUsersRequest
	14,  // 14: nakama.api.Nakama.BlockFriends:input_type -> nakama.api.BlockFriendsRequest
	15,  // 15: nakama.api.Nakama.CreateGroup:input_type -> nakama.api.CreateGroupRequest
	16,  // 16: nakama.api.Nakama.DeleteAccount:input_type -> google.protobuf.Empty
	17,  // 17: nakama.api.Nakama.DeleteFriends:input_type -> nakama.api.DeleteFriendsRequest
	18,  // 18: nakama.api.Nakama.DeleteGroup:input_type -> nakama.api.DeleteGroupRequest
	19,  // 19: nakama.api.Nakama.DeleteLeaderboardRecord:input_type -> nakama.api.DeleteLeaderboardRecordRequest
	20,  // 20: nakama.api.Nakama.DeleteNotifications:input_type -> nakama.api.DeleteNotificationsRequest
	21,  // 21: nakama.api.Nakama.DeleteTournamentRecord:input_type -> nakama.api.DeleteTournamentRecordRequest
	22,  // 22: nakama.api.Nakama.DeleteStorageObjects:input_type -> nakama.api.DeleteStorageObjectsRequest
	23,  // 23: nakama.api.Nakama.Event:input_type -> nakama.api.Event
	16,  // 24: nakama.api.Nakama.GetAccount:input_type -> google.protobuf.Empty
	24,  // 25: nakama.api.Nakama.GetUsers:input_type -> nakama.api.GetUsersRequest
	25,  // 26: nakama.api.Nakama.GetSubscription:input_type -> nakama.api.GetSubscriptionRequest
	16,  // 27: nakama.api.Nakama.GetMatchmakerStats:input_type -> google.protobuf.Empty
	16,  // 28: nakama.api.Nakama.Healthcheck:input_type -> google.protobuf.Empty
	26,  // 29: nakama.api.Nakama.ImportFacebookFriends:input_type -> nakama.api.ImportFacebookFriendsRequest
	27,  // 30: nakama.api.Nakama.ImportSteamFriends:input_type -> nakama.api.ImportSteamFriendsRequest
	28,  // 31: nakama.api.Nakama.JoinGroup:input_type -> nakama.api.JoinGroupRequest
	29,  // 32: nakama.api.Nakama.JoinTournament:input_type -> nakama.api.JoinTournamentRequest
	30,  // 33: nakama.api.Nakama.KickGroupUsers:input_type -> nakama.api.KickGroupUsersRequest
	31,  // 34: nakama.api.Nakama.LeaveGroup:input_type -> nakama.api.LeaveGroupRequest
	32,  // 35: nakama.api.Nakama.LinkApple:input_type -> nakama.api.AccountApple
	33,  // 36: nakama.api.Nakama.LinkCustom:input_type -> nakama.api.AccountCustom
	34,  // 37: nakama.api.Nakama.LinkDevice:input_type -> nakama.api.AccountDevice
	35,  // 38: nakama.api.Nakama.LinkEmail:input_type -> nakama.api.AccountEmail
	36,  // 39: nakama.api.Nakama.LinkFacebook:input_type -> nakama.api.LinkFacebookRequest
	37,  // 40: nakama.api.Nakama.LinkFacebookInstantGame:input_type -> nakama.api.AccountFacebookInstantGame
	38,  // 41: nakama.api.Nakama.LinkGameCenter:input_type -> nakama.api.AccountGameCenter
	39,  // 42: nakama.api.Nakama.LinkGoogle:input_type -> nakama.api.AccountGoogle
	40,  // 43: nakama.api.Nakama.LinkSteam:input_type -> nakama.api.LinkSteamRequest
	41,  // 44: nakama.api.Nakama.ListChannelMessages:input_type -> nakama.api.ListChannelMessagesRequest
	42,  // 45: nakama.api.Nakama.ListFriends:input_type -> nakama.api.ListFriendsRequest
	43,  // 46: nakama.api.Nakama.ListFriendsOfFriends:input_type -> nakama.api.ListFriendsOfFriendsRequest
	44,  // 47: nakama.api.Nakama.ListGroups:input_type -> nakama.api.ListGroupsRequest
	45,  // 48: nakama.api.Nakama.ListGroupUsers:input_type -> nakama.api.ListGroupUsersRequest
	46,  // 49: nakama.api.Nakama.ListLeaderboardRecords:input_type -> nakama.api.ListLeaderboardRecordsRequest
	47,  // 50: nakama.api.Nakama.ListLeaderboardRecordsAroundOwner:input_type -> nakama.api.ListLeaderboardRecordsAroundOwnerRequest
	48,  // 51: nakama.api.Nakama.ListMatches:input_type -> nakama.api.ListMatchesRequest
	49,  // 52: nakama.api.Nakama.ListNotifications:input_type -> nakama.api.ListNotificationsRequest
	50,  // 53: nakama.api.Nakama.ListStorageObjects:input_type -> nakama.api.ListStorageObjectsRequest
	51,  // 54: nakama.api.Nakama.ListSubscriptions:input_type -> nakama.api.ListSubscriptionsRequest
	52,  // 55: nakama.api.Nakama.ListTournaments:input_type -> nakama.api.ListTournamentsRequest
	53,  // 56: nakama.api.Nakama.ListTournamentRecords:input_type -> nakama.api.ListTournamentRecordsRequest
	54,  // 57: nakama.api.Nakama.ListTournamentRecordsAroundOwner:input_type -> nakama.api.ListTournamentRecordsAroundOwnerRequest
	55,  // 58: nakama.api.Nakama.ListUserGroups:input_type -> nakama.api.ListUserGroupsRequest
	56,  // 59: nakama.api.Nakama.PromoteGroupUsers:input_type -> nakama.api.PromoteGroupUsersRequest
	57,  // 60: nakama.api.Nakama.DemoteGroupUsers:input_type -> nakama.api.DemoteGroupUsersRequest
	58,  // 61: nakama.api.Nakama.ReadStorageObjects:input_type -> nakama.api.ReadStorageObjectsRequest
	59,  // 62: nakama.api.Nakama.RpcFunc:input_type -> nakama.api.Rpc
	32,  // 63: nakama.api.Nakama.UnlinkApple:input_type -> nakama.api.AccountApple
	33,  // 64: nakama.api.Nakama.UnlinkCustom:input_type -> nakama.api.AccountCustom
	34,  // 65: nakama.api.Nakama.UnlinkDevice:input_type -> nakama.api.AccountDevice
	35,  // 66: nakama.api.Nakama.UnlinkEmail:input_type -> nakama.api.AccountEmail
	60,  // 67: nakama.api.Nakama.UnlinkFacebook:input_type -> nakama.api.AccountFacebook
	37,  // 68: nakama.api.Nakama.UnlinkFacebookInstantGame:input_type -> nakama.api.AccountFacebookInstantGame
	38,  // 69: nakama.api.Nakama.UnlinkGameCenter:input_type -> nakama.api.AccountGameCenter
	39,  // 70: nakama.api.Nakama.UnlinkGoogle:input_type -> nakama.api.AccountGoogle
	61,  // 71: nakama.api.Nakama.UnlinkSteam:input_type -> nakama.api.AccountSteam
	62,  // 72: nakama.api.Nakama.UpdateAccount:input_type -> nakama.api.UpdateAccountRequest
	63,  // 73: nakama.api.Nakama.UpdateGroup:input_type -> nakama.api.UpdateGroupRequest
	64,  // 74: nakama.api.Nakama.ValidatePurchaseApple:input_type -> nakama.api.ValidatePurchaseAppleRequest
	65,  // 75: nakama.api.Nakama.ValidateSubscriptionApple:input_type -> nakama.api.ValidateSubscriptionAppleRequest
	66,  // 76: nakama.api.Nakama.ValidatePurchaseGoogle:input_type -> nakama.api.ValidatePurchaseGoogleRequest
	67,  // 77: nakama.api.Nakama.ValidateSubscriptionGoogle:input_type -> nakama.api.ValidateSubscriptionGoogleRequest
	68,  // 78: nakama.api.Nakama.ValidatePurchaseHuawei:input_type -> nakama.api.ValidatePurchaseHuaweiRequest
	69,  // 79: nakama.api.Nakama.ValidatePurchaseFacebookInstant:input_type -> nakama.api.ValidatePurchaseFacebookInstantRequest
	70,  // 80: nakama.api.Nakama.WriteLeaderboardRecord:input_type -> nakama.api.WriteLeaderboardRecordRequest
	71,  // 81: nakama.api.Nakama.WriteStorageObjects:input_type -> nakama.api.WriteStorageObjectsRequest
	72,  // 82: nakama.api.Nakama.WriteTournamentRecord:input_type -> nakama.api.WriteTournamentRecordRequest
	73,  // 83: nakama.api.Nakama.RedeemGift:input_type -> game.RedeemGiftRequest
	74,  // 84: nakama.api.Nakama.Feedback:input_type -> game.FeedbackRequest
	75,  // 85: nakama.api.Nakama.AuthenticateWechat:input_type -> game.AuthenticateWechatRequest
	76,  // 86: nakama.api.Nakama.AuthenticateTikTok:input_type -> game.AuthenticateTiktokRequest
	77,  // 87: nakama.api.Nakama.SubmitBeInvited:input_type -> game.SubmitBeInvitedRequest
	16,  // 88: nakama.api.Nakama.ListInvitee:input_type -> google.protobuf.Empty
	78,  // 89: nakama.api.Nakama.ClaimInviteReward:input_type -> game.ClaimInviteRewardRequest
	79,  // 90: nakama.api.Nakama.ClaimByteReward:input_type -> game.ClaimByteRewardRequest
	16,  // 91: nakama.api.Nakama.GetGameTime:input_type -> google.protobuf.Empty
	80,  // 92: nakama.api.Nakama.ListPublishedAnnouncements:input_type -> game.ListPublishedAnnouncementsRequest
	81,  // 93: nakama.api.Nakama.MarkNotificationsRead:input_type -> game.MarkNotificationsReadRequest
	82,  // 94: nakama.api.Nakama.ClaimNotificationAttachments:input_type -> game.ClaimNotificationAttachmentsRequest
	16,  // 95: nakama.api.Nakama.GetCurrentStamina:input_type -> google.protobuf.Empty
	16,  // 96: nakama.api.Nakama.GetEquipData:input_type -> google.protobuf.Empty
	83,  // 97: nakama.api.Nakama.OperateWallet:input_type -> game.OperateWalletRequest
	84,  // 98: nakama.api.Nakama.GetWalletData:input_type -> game.GetWalletDataRequest
	85,  // 99: nakama.api.Nakama.OperateInventory:input_type -> game.OperateInventoryRequest
	86,  // 100: nakama.api.Nakama.GetInventoryData:input_type -> game.GetInventoryDataRequest
	16,  // 101: nakama.api.Nakama.GetShopData:input_type -> google.protobuf.Empty
	87,  // 102: nakama.api.Nakama.BuyShopItem:input_type -> game.BuyShopItemRequest
	88,  // 103: nakama.api.Nakama.RefreshShop:input_type -> game.RefreshShopRequest
	16,  // 104: nakama.api.Nakama.GetBoxShop:input_type -> google.protobuf.Empty
	89,  // 105: nakama.api.Nakama.BuyBoxItem:input_type -> game.BuyBoxItemRequest
	16,  // 106: nakama.api.Nakama.GetChapterShop:input_type -> google.protobuf.Empty
	90,  // 107: nakama.api.Nakama.ClaimChapterItem:input_type -> game.ClaimChapterItemRequest
	16,  // 108: nakama.api.Nakama.GetGemShop:input_type -> google.protobuf.Empty
	91,  // 109: nakama.api.Nakama.ClaimGemItem:input_type -> game.ClaimGemItemRequest
	92,  // 110: nakama.api.Nakama.EndBattle:input_type -> game.EndBattleRequest
	93,  // 111: nakama.api.Nakama.StartBattle:input_type -> game.StartBattleRequest
	94,  // 112: nakama.api.Nakama.ClaimBattleRewardByShare:input_type -> game.ClaimBattleRewardByShareRequest
	95,  // 113: nakama.api.Nakama.ClaimMoppingReward:input_type -> game.ClaimMoppingRewardRequest
	96,  // 114: nakama.api.Nakama.ClaimOnHookReward:input_type -> game.ClaimOnHookRewardRequest
	97,  // 115: nakama.api.Nakama.UpgradeEquip:input_type -> game.UpgradeEquipRequest
	98,  // 116: nakama.api.Nakama.UpgradeCrystalTech:input_type -> game.UpgradeCrystalTechRequest
	99,  // 117: nakama.api.Nakama.ClaimLevelBox:input_type -> game.ClaimLevelBoxRequest
	100, // 118: nakama.api.Nakama.GetLevelBox:input_type -> game.GetLevelBoxRequest
	101, // 119: nakama.api.Nakama.ClaimSignInReward:input_type -> game.ClaimSignInRewardRequest
	16,  // 120: nakama.api.Nakama.GetSignInReward:input_type -> google.protobuf.Empty
	102, // 121: nakama.api.Nakama.GetFirstChargeStatus:input_type -> game.GetFirstChargeStatusRequest
	103, // 122: nakama.api.Nakama.ClaimFirstChargeReward:input_type -> game.ClaimFirstChargeRewardRequest
	104, // 123: nakama.api.Nakama.GetTask:input_type -> game.GetTaskRequest
	105, // 124: nakama.api.Nakama.ClaimTaskReward:input_type -> game.ClaimTaskRewardRequest
	106, // 125: nakama.api.Nakama.ClaimLivenessReward:input_type -> game.ClaimLivenessRewardRequest
	107, // 126: nakama.api.Nakama.ClaimVipReward:input_type -> game.ClaimVipRewardRequest
	16,  // 127: nakama.api.Nakama.CheckVipStatus:input_type -> google.protobuf.Empty
	108, // 128: nakama.api.Nakama.GetSevenDayStatus:input_type -> game.GetSevenDayStatusRequest
	109, // 129: nakama.api.Nakama.ClaimSevenDayReward:input_type -> game.ClaimSevenDayRewardRequest
	16,  // 130: nakama.api.Nakama.GetChallenge:input_type -> google.protobuf.Empty
	110, // 131: nakama.api.Nakama.JoinChallenge:input_type -> game.JoinChallengeRequest
	111, // 132: nakama.api.Nakama.GainChallengeReward:input_type -> game.GainChallengeRewardRequest
	16,  // 133: nakama.api.Nakama.GetChallengeTopStats:input_type -> google.protobuf.Empty
	112, // 134: nakama.api.Nakama.GetChallengeBattleTimes:input_type -> game.GetChallengeBattleTimesRequest
	113, // 135: nakama.api.Nakama.BuyChallengeBattleTimes:input_type -> game.BuyChallengeBattleTimesRequest
	114, // 136: nakama.api.Nakama.PurchaseTest:input_type -> game.PurchaseRequest
	16,  // 137: nakama.api.Nakama.AddFriends:output_type -> google.protobuf.Empty
	16,  // 138: nakama.api.Nakama.AddGroupUsers:output_type -> google.protobuf.Empty
	115, // 139: nakama.api.Nakama.SessionRefresh:output_type -> nakama.api.Session
	16,  // 140: nakama.api.Nakama.SessionLogout:output_type -> google.protobuf.Empty
	115, // 141: nakama.api.Nakama.AuthenticateApple:output_type -> nakama.api.Session
	115, // 142: nakama.api.Nakama.AuthenticateCustom:output_type -> nakama.api.Session
	115, // 143: nakama.api.Nakama.AuthenticateDevice:output_type -> nakama.api.Session
	115, // 144: nakama.api.Nakama.AuthenticateEmail:output_type -> nakama.api.Session
	115, // 145: nakama.api.Nakama.AuthenticateFacebook:output_type -> nakama.api.Session
	115, // 146: nakama.api.Nakama.AuthenticateFacebookInstantGame:output_type -> nakama.api.Session
	115, // 147: nakama.api.Nakama.AuthenticateGameCenter:output_type -> nakama.api.Session
	115, // 148: nakama.api.Nakama.AuthenticateGoogle:output_type -> nakama.api.Session
	115, // 149: nakama.api.Nakama.AuthenticateSteam:output_type -> nakama.api.Session
	16,  // 150: nakama.api.Nakama.BanGroupUsers:output_type -> google.protobuf.Empty
	16,  // 151: nakama.api.Nakama.BlockFriends:output_type -> google.protobuf.Empty
	116, // 152: nakama.api.Nakama.CreateGroup:output_type -> nakama.api.Group
	16,  // 153: nakama.api.Nakama.DeleteAccount:output_type -> google.protobuf.Empty
	16,  // 154: nakama.api.Nakama.DeleteFriends:output_type -> google.protobuf.Empty
	16,  // 155: nakama.api.Nakama.DeleteGroup:output_type -> google.protobuf.Empty
	16,  // 156: nakama.api.Nakama.DeleteLeaderboardRecord:output_type -> google.protobuf.Empty
	16,  // 157: nakama.api.Nakama.DeleteNotifications:output_type -> google.protobuf.Empty
	16,  // 158: nakama.api.Nakama.DeleteTournamentRecord:output_type -> google.protobuf.Empty
	16,  // 159: nakama.api.Nakama.DeleteStorageObjects:output_type -> google.protobuf.Empty
	16,  // 160: nakama.api.Nakama.Event:output_type -> google.protobuf.Empty
	117, // 161: nakama.api.Nakama.GetAccount:output_type -> nakama.api.Account
	118, // 162: nakama.api.Nakama.GetUsers:output_type -> nakama.api.Users
	119, // 163: nakama.api.Nakama.GetSubscription:output_type -> nakama.api.ValidatedSubscription
	120, // 164: nakama.api.Nakama.GetMatchmakerStats:output_type -> nakama.api.MatchmakerStats
	16,  // 165: nakama.api.Nakama.Healthcheck:output_type -> google.protobuf.Empty
	16,  // 166: nakama.api.Nakama.ImportFacebookFriends:output_type -> google.protobuf.Empty
	16,  // 167: nakama.api.Nakama.ImportSteamFriends:output_type -> google.protobuf.Empty
	16,  // 168: nakama.api.Nakama.JoinGroup:output_type -> google.protobuf.Empty
	16,  // 169: nakama.api.Nakama.JoinTournament:output_type -> google.protobuf.Empty
	16,  // 170: nakama.api.Nakama.KickGroupUsers:output_type -> google.protobuf.Empty
	16,  // 171: nakama.api.Nakama.LeaveGroup:output_type -> google.protobuf.Empty
	16,  // 172: nakama.api.Nakama.LinkApple:output_type -> google.protobuf.Empty
	16,  // 173: nakama.api.Nakama.LinkCustom:output_type -> google.protobuf.Empty
	16,  // 174: nakama.api.Nakama.LinkDevice:output_type -> google.protobuf.Empty
	16,  // 175: nakama.api.Nakama.LinkEmail:output_type -> google.protobuf.Empty
	16,  // 176: nakama.api.Nakama.LinkFacebook:output_type -> google.protobuf.Empty
	16,  // 177: nakama.api.Nakama.LinkFacebookInstantGame:output_type -> google.protobuf.Empty
	16,  // 178: nakama.api.Nakama.LinkGameCenter:output_type -> google.protobuf.Empty
	16,  // 179: nakama.api.Nakama.LinkGoogle:output_type -> google.protobuf.Empty
	16,  // 180: nakama.api.Nakama.LinkSteam:output_type -> google.protobuf.Empty
	121, // 181: nakama.api.Nakama.ListChannelMessages:output_type -> nakama.api.ChannelMessageList
	122, // 182: nakama.api.Nakama.ListFriends:output_type -> nakama.api.FriendList
	123, // 183: nakama.api.Nakama.ListFriendsOfFriends:output_type -> nakama.api.FriendsOfFriendsList
	124, // 184: nakama.api.Nakama.ListGroups:output_type -> nakama.api.GroupList
	125, // 185: nakama.api.Nakama.ListGroupUsers:output_type -> nakama.api.GroupUserList
	126, // 186: nakama.api.Nakama.ListLeaderboardRecords:output_type -> nakama.api.LeaderboardRecordList
	126, // 187: nakama.api.Nakama.ListLeaderboardRecordsAroundOwner:output_type -> nakama.api.LeaderboardRecordList
	127, // 188: nakama.api.Nakama.ListMatches:output_type -> nakama.api.MatchList
	128, // 189: nakama.api.Nakama.ListNotifications:output_type -> nakama.api.NotificationList
	129, // 190: nakama.api.Nakama.ListStorageObjects:output_type -> nakama.api.StorageObjectList
	130, // 191: nakama.api.Nakama.ListSubscriptions:output_type -> nakama.api.SubscriptionList
	131, // 192: nakama.api.Nakama.ListTournaments:output_type -> nakama.api.TournamentList
	132, // 193: nakama.api.Nakama.ListTournamentRecords:output_type -> nakama.api.TournamentRecordList
	132, // 194: nakama.api.Nakama.ListTournamentRecordsAroundOwner:output_type -> nakama.api.TournamentRecordList
	133, // 195: nakama.api.Nakama.ListUserGroups:output_type -> nakama.api.UserGroupList
	16,  // 196: nakama.api.Nakama.PromoteGroupUsers:output_type -> google.protobuf.Empty
	16,  // 197: nakama.api.Nakama.DemoteGroupUsers:output_type -> google.protobuf.Empty
	134, // 198: nakama.api.Nakama.ReadStorageObjects:output_type -> nakama.api.StorageObjects
	59,  // 199: nakama.api.Nakama.RpcFunc:output_type -> nakama.api.Rpc
	16,  // 200: nakama.api.Nakama.UnlinkApple:output_type -> google.protobuf.Empty
	16,  // 201: nakama.api.Nakama.UnlinkCustom:output_type -> google.protobuf.Empty
	16,  // 202: nakama.api.Nakama.UnlinkDevice:output_type -> google.protobuf.Empty
	16,  // 203: nakama.api.Nakama.UnlinkEmail:output_type -> google.protobuf.Empty
	16,  // 204: nakama.api.Nakama.UnlinkFacebook:output_type -> google.protobuf.Empty
	16,  // 205: nakama.api.Nakama.UnlinkFacebookInstantGame:output_type -> google.protobuf.Empty
	16,  // 206: nakama.api.Nakama.UnlinkGameCenter:output_type -> google.protobuf.Empty
	16,  // 207: nakama.api.Nakama.UnlinkGoogle:output_type -> google.protobuf.Empty
	16,  // 208: nakama.api.Nakama.UnlinkSteam:output_type -> google.protobuf.Empty
	16,  // 209: nakama.api.Nakama.UpdateAccount:output_type -> google.protobuf.Empty
	16,  // 210: nakama.api.Nakama.UpdateGroup:output_type -> google.protobuf.Empty
	135, // 211: nakama.api.Nakama.ValidatePurchaseApple:output_type -> nakama.api.ValidatePurchaseResponse
	136, // 212: nakama.api.Nakama.ValidateSubscriptionApple:output_type -> nakama.api.ValidateSubscriptionResponse
	135, // 213: nakama.api.Nakama.ValidatePurchaseGoogle:output_type -> nakama.api.ValidatePurchaseResponse
	136, // 214: nakama.api.Nakama.ValidateSubscriptionGoogle:output_type -> nakama.api.ValidateSubscriptionResponse
	135, // 215: nakama.api.Nakama.ValidatePurchaseHuawei:output_type -> nakama.api.ValidatePurchaseResponse
	135, // 216: nakama.api.Nakama.ValidatePurchaseFacebookInstant:output_type -> nakama.api.ValidatePurchaseResponse
	137, // 217: nakama.api.Nakama.WriteLeaderboardRecord:output_type -> nakama.api.LeaderboardRecord
	138, // 218: nakama.api.Nakama.WriteStorageObjects:output_type -> nakama.api.StorageObjectAcks
	137, // 219: nakama.api.Nakama.WriteTournamentRecord:output_type -> nakama.api.LeaderboardRecord
	139, // 220: nakama.api.Nakama.RedeemGift:output_type -> game.RedeemGiftResponse
	16,  // 221: nakama.api.Nakama.Feedback:output_type -> google.protobuf.Empty
	115, // 222: nakama.api.Nakama.AuthenticateWechat:output_type -> nakama.api.Session
	115, // 223: nakama.api.Nakama.AuthenticateTikTok:output_type -> nakama.api.Session
	16,  // 224: nakama.api.Nakama.SubmitBeInvited:output_type -> google.protobuf.Empty
	140, // 225: nakama.api.Nakama.ListInvitee:output_type -> game.ListInviteeResponse
	141, // 226: nakama.api.Nakama.ClaimInviteReward:output_type -> game.ClaimInviteRewardResponse
	142, // 227: nakama.api.Nakama.ClaimByteReward:output_type -> game.ClaimByteRewardResponse
	143, // 228: nakama.api.Nakama.GetGameTime:output_type -> game.GetGameTimeResponse
	144, // 229: nakama.api.Nakama.ListPublishedAnnouncements:output_type -> game.ListPublishedAnnouncementsResponse
	145, // 230: nakama.api.Nakama.MarkNotificationsRead:output_type -> game.MarkNotificationsReadResponse
	146, // 231: nakama.api.Nakama.ClaimNotificationAttachments:output_type -> game.ClaimNotificationAttachmentsResponse
	147, // 232: nakama.api.Nakama.GetCurrentStamina:output_type -> game.StaminaData
	148, // 233: nakama.api.Nakama.GetEquipData:output_type -> game.EquipData
	149, // 234: nakama.api.Nakama.OperateWallet:output_type -> game.OperateWalletResponse
	150, // 235: nakama.api.Nakama.GetWalletData:output_type -> game.GetWalletDataResponse
	151, // 236: nakama.api.Nakama.OperateInventory:output_type -> game.OperateInventoryResponse
	152, // 237: nakama.api.Nakama.GetInventoryData:output_type -> game.GetInventoryDataResponse
	153, // 238: nakama.api.Nakama.GetShopData:output_type -> game.ShopData
	154, // 239: nakama.api.Nakama.BuyShopItem:output_type -> game.BuyShopItemResponse
	155, // 240: nakama.api.Nakama.RefreshShop:output_type -> game.RefreshShopResponse
	156, // 241: nakama.api.Nakama.GetBoxShop:output_type -> game.BoxShopData
	157, // 242: nakama.api.Nakama.BuyBoxItem:output_type -> game.BuyBoxItemResponse
	158, // 243: nakama.api.Nakama.GetChapterShop:output_type -> game.ChapterShopData
	159, // 244: nakama.api.Nakama.ClaimChapterItem:output_type -> game.ClaimChapterItemResponse
	160, // 245: nakama.api.Nakama.GetGemShop:output_type -> game.GemShopData
	161, // 246: nakama.api.Nakama.ClaimGemItem:output_type -> game.ClaimGemItemResponse
	162, // 247: nakama.api.Nakama.EndBattle:output_type -> game.EndBattleResponse
	163, // 248: nakama.api.Nakama.StartBattle:output_type -> game.StartBattleResponse
	164, // 249: nakama.api.Nakama.ClaimBattleRewardByShare:output_type -> game.ClaimBattleRewardByShareResponse
	165, // 250: nakama.api.Nakama.ClaimMoppingReward:output_type -> game.ClaimMoppingRewardResponse
	166, // 251: nakama.api.Nakama.ClaimOnHookReward:output_type -> game.ClaimOnHookRewardResponse
	167, // 252: nakama.api.Nakama.UpgradeEquip:output_type -> game.UpgradeEquipResponse
	168, // 253: nakama.api.Nakama.UpgradeCrystalTech:output_type -> game.UpgradeCrystalTechResponse
	169, // 254: nakama.api.Nakama.ClaimLevelBox:output_type -> game.ClaimLevelBoxResponse
	170, // 255: nakama.api.Nakama.GetLevelBox:output_type -> game.GetLevelBoxResponse
	171, // 256: nakama.api.Nakama.ClaimSignInReward:output_type -> game.ClaimSignInRewardResponse
	172, // 257: nakama.api.Nakama.GetSignInReward:output_type -> game.GetSignInRewardResponse
	173, // 258: nakama.api.Nakama.GetFirstChargeStatus:output_type -> game.GetFirstChargeStatusResponse
	174, // 259: nakama.api.Nakama.ClaimFirstChargeReward:output_type -> game.ClaimFirstChargeRewardResponse
	175, // 260: nakama.api.Nakama.GetTask:output_type -> game.GetTaskResponse
	176, // 261: nakama.api.Nakama.ClaimTaskReward:output_type -> game.ClaimTaskRewardResponse
	177, // 262: nakama.api.Nakama.ClaimLivenessReward:output_type -> game.ClaimLivenessRewardResponse
	178, // 263: nakama.api.Nakama.ClaimVipReward:output_type -> game.ClaimVipRewardResponse
	179, // 264: nakama.api.Nakama.CheckVipStatus:output_type -> game.CheckVipStatusResponse
	180, // 265: nakama.api.Nakama.GetSevenDayStatus:output_type -> game.GetSevenDayStatusResponse
	181, // 266: nakama.api.Nakama.ClaimSevenDayReward:output_type -> game.ClaimSevenDayRewardResponse
	182, // 267: nakama.api.Nakama.GetChallenge:output_type -> game.GetChallengeResponse
	183, // 268: nakama.api.Nakama.JoinChallenge:output_type -> game.JoinChallengeResponse
	184, // 269: nakama.api.Nakama.GainChallengeReward:output_type -> game.GainChallengeRewardResponse
	185, // 270: nakama.api.Nakama.GetChallengeTopStats:output_type -> game.GetChallengeTopStatsResponse
	186, // 271: nakama.api.Nakama.GetChallengeBattleTimes:output_type -> game.GetChallengeBattleTimesResponse
	187, // 272: nakama.api.Nakama.BuyChallengeBattleTimes:output_type -> game.BuyChallengeBattleTimesResponse
	188, // 273: nakama.api.Nakama.PurchaseTest:output_type -> game.PurchaseResponse
	137, // [137:274] is the sub-list for method output_type
	0,   // [0:137] is the sub-list for method input_type
	0,   // [0:0] is the sub-list for extension type_name
	0,   // [0:0] is the sub-list for extension extendee
	0,   // [0:0] is the sub-list for field type_name
}

func init() { file_apigrpc_proto_init() }
func file_apigrpc_proto_init() {
	if File_apigrpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apigrpc_proto_rawDesc), len(file_apigrpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apigrpc_proto_goTypes,
		DependencyIndexes: file_apigrpc_proto_depIdxs,
	}.Build()
	File_apigrpc_proto = out.File
	file_apigrpc_proto_goTypes = nil
	file_apigrpc_proto_depIdxs = nil
}
